### ISSUE TITLE
`GetAppDataCommon` not exposed to JS api

### ISSUE THREAD

**Issue by danielgindi** [kingjan1999/platform-folders#10]
Hi!

This folder is quite an important one, but `GetAppDataCommon` is not exposed.

**Comment by kingjan1999** [comment]
Hi!

Thanks for your interest in this project! I've just published version 0.4.0 on npm, which includes `getDataFolders` and `getConfigFolders`.

As `GetAppDataCommon`is windows-specific I can't just expose it (it's not even included in the header file of the underlying library). However it is used for `appendAdditionalDataDirectories`  and `appendAdditionalConfigDirectories` as an extra folder programs should look in when looking for data / config files.

I've "translated" these methods to the aforementioned `get*Folders` methods. These should return arrays with just one element - the result of `GetAppDataCommon` - on Windows.

This may not be the most direct solution to receive the result of `GetAppDataCommon` but IMO the most clean one.

**Comment by danielgindi** [comment]
Well as long as it's stable and everyone knows that on Windows the first item in the array is `GetAppDataCommon()` then that's fine :-)

Thank you!
