### ISSUE TITLE
How to access System Environment.SpecialFolder.CommonApplicationData?

### ISSUE THREAD

**Issue by JohnyHHH** [kingjan1999/platform-folders#12]
Hi, may i know is that possible to get Environment.SpecialFolder.CommonApplicationData using this platform-folders? 

What is the exported function getDataFolders() refer to? As mentioned the results is array, what are those results represent?  

Thanks.

**Comment by kingjan1999** [comment]
Hi,

you can use both `getDataFolders()` and `getConfigFolders()` for this. On Windows they both return a one element array containing `CSIDL_COMMON_APPDATA` (which is the C++ equivalent of `Environment.SpecialFolder.CommonApplicationData`, i.e. `C:\Program Data` for Vista +).

The behavior of `getDataFolders` (and `getConfigFolders`) varies on a per OS-basis. On Windows, both return a one element array containing common appdata (as described above), on OS X both return an empty array and on Linux they return the contents of `$XDG_DATA_DIRS` + `/usr/local/share/` + `/usr/share` (for `getDataFolders`, for `getConfigFolders` it's `$XDG_CONFIG_DIRS` + `/etc/xdg`)

Hope this helps!

**Comment by JohnyHHH** [comment]
Hi, thanks a lot for the feedback.
