### ISSUE TITLE
electron下直接用这个包，获取用户路径，进程崩溃

### ISSUE THREAD

**Issue by Jack-0105** [kingjan1999/platform-folders#14]

**Comment by kingjan1999** [comment]
Hi,

thanks for the report. While I'll certainly look at this tomorrow, I'd recommend using Electron's  [`app.getPath`](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetpathname) as it's probably more stable and more feature-rich when Electron is already there.

**Comment by kingjan1999** [comment]
Hi,

I've just tested this using v0.5.1 of this library and v9.0.3 of Electron and were unable to reproduce this issue. Can you provide me with a minimal example to reproduce the crash?
