### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by DanielRuf** [kingjan1999/platform-folders#3]
```
$ npm i platform-folders -S

> platform-folders@0.2.1 install C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
> node-gyp rebuild


C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  binding.cc
  platform_folders.cpp
  win_delay_load_hook.cc
..\binding.cc(12): warning C4530: C++ exception handler used, but unwind semant
ics are not enabled. Specify /EHsc [C:\Users\Daniel\GITHUB\node-savegames\node_
modules\platform-folders\build\platform-folders.vcxproj]
..\platform_folders.cpp(373): error C2664: 'std::string GetWindowsFolder(int,co
nst char *)': cannot convert argument 1 from 'const GUID' to 'int' [C:\Users\Da
niel\GITHUB\node-savegames\node_modules\platform-folders\build\platform-folders
.vcxproj]
  ..\platform_folders.cpp(373): note: No user-defined-conversion operator avail
  able that can perform this conversion, or the operator cannot be called
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN node-savegames@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! platform-folders@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the platform-folders@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2018-04-16T21_13_57_909Z-debug.log
```

**Comment by kingjan1999** [comment]
Damn, just use 0.1.5, for now, I will look into it tomorrow

**Comment by DanielRuf** [comment]
0.1.5 works so far

**Comment by kingjan1999** [comment]
I've just published v0.2.2 on npm, which should fix this. Would you mind testing it again?

**Comment by DanielRuf** [comment]
Thanks for the update, I will test it this evening when I am on my Windows machine. I'm currently at work and work with macOS here so I guess I can not yet test it (but this evening).

**Comment by DanielRuf** [comment]
Installation works now but it seems .git is not in the npmignore file or there is something else which is creating `.git`.

```
$ npm i platform-folders@0.2.2
npm ERR! path C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
npm ERR! code EISGIT
npm ERR! git C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2018-04-17T18_09_16_079Z-debug.log
```

**Comment by kingjan1999** [comment]
That's strange as npm [should ignore .git by default](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). I published 0.2.3, which should exclude .git.

Sorry for the inconvenience.

**Comment by DanielRuf** [comment]
Perfect, works now also with subsequent installs.

<details>
<summary>output of two install commands</summary>
Daniel@Daniel-MSI MINGW64 ~/GITHUB/node-savegames (master)
$ npm i platform-folders@0.2.3

> platform-folders@0.2.3 install C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
> node-gyp rebuild


C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  binding.cc
  platform_folders.cpp
  win_delay_load_hook.cc
..\binding.cc(12): warning C4530: C++ exception handler used, but unwind semant
ics are not enabled. Specify /EHsc [C:\Users\Daniel\GITHUB\node-savegames\node_
modules\platform-folders\build\platform-folders.vcxproj]
     Creating library C:\Users\Daniel\GITHUB\node-savegames\node_modules\platfo
  rm-folders\build\Release\platform-folders.lib and object C:\Users\Daniel\GITH
  UB\node-savegames\node_modules\platform-folders\build\Release\platform-folder
  s.exp
  Generating code
  All 174 functions were compiled because no usable IPDB/IOBJ from previous com
  pilation was found.
  Finished generating code
  platform-folders.vcxproj -> C:\Users\Daniel\GITHUB\node-savegames\node_module
  s\platform-folders\build\Release\\platform-folders.node
  platform-folders.vcxproj -> C:\Users\Daniel\GITHUB\node-savegames\node_module
  s\platform-folders\build\Release\platform-folders.pdb (Full PDB)
npm WARN node-savegames@1.0.0 No description

+ platform-folders@0.2.3
added 1 package in 15.171s

Daniel@Daniel-MSI MINGW64 ~/GITHUB/node-savegames (master)
$ npm i platform-folders@0.2.3

> platform-folders@0.2.3 install C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders
> node-gyp rebuild


C:\Users\Daniel\GITHUB\node-savegames\node_modules\platform-folders>if not defined npm_config_node_gyp (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  binding.cc
  platform_folders.cpp
  win_delay_load_hook.cc
..\binding.cc(12): warning C4530: C++ exception handler used, but unwind semant
ics are not enabled. Specify /EHsc [C:\Users\Daniel\GITHUB\node-savegames\node_
modules\platform-folders\build\platform-folders.vcxproj]
     Creating library C:\Users\Daniel\GITHUB\node-savegames\node_modules\platfo
  rm-folders\build\Release\platform-folders.lib and object C:\Users\Daniel\GITH
  UB\node-savegames\node_modules\platform-folders\build\Release\platform-folder
  s.exp
  Generating code
  All 174 functions were compiled because no usable IPDB/IOBJ from previous com
  pilation was found.
  Finished generating code
  platform-folders.vcxproj -> C:\Users\Daniel\GITHUB\node-savegames\node_module
  s\platform-folders\build\Release\\platform-folders.node
  platform-folders.vcxproj -> C:\Users\Daniel\GITHUB\node-savegames\node_module
  s\platform-folders\build\Release\platform-folders.pdb (Full PDB)
npm WARN node-savegames@1.0.0 No description

+ platform-folders@0.2.3
updated 1 package in 4.643s
</details>

**Comment by DanielRuf** [comment]
Thanks for taking care of this so fast and creating `platform-folders`.
