### ISSUE TITLE
add substitutePath

### ISSUE THREAD

**Issue by k2s** [kingjan1999/platform-folders#5]
would you agree to add to your library function which will substitute the folder names when used in path ?

something like:
```js
export function substitutePath (folder) {
  if (folder.startsWith('~')) {
    return getPlatformFolder('home') + folder.substr(1)
  }
  return folder.replace(/^%([^%]+)%/, function (_, n) {
    return getPlatformFolder(n.toLowerCase())
  })
}

substitutePath('~/mydir')
substitutePath('%home%/mydir')
substitutePath('%appData%/mydir')
```

**Comment by kingjan1999** [comment]
Hi,

thanks for your interest in `platform-folders` and suggesting ways to improve it. I'm not sure how I should feel about your suggestion, as I am not sure whether this is out of scope or not.

But since there seems to be a need for it, feel free to open a pull request!

**Comment by k2s** [comment]
Hello,
I think this function doesn't fit this library. There could be many ways to do the substitution and the way I presented in this ticket should not make this library less universal.

Thank you.
