### ISSUE TITLE
0.2.5 can't load the native library

### ISSUE THREAD

**Issue by k2s** [kingjan1999/platform-folders#6]
You removed `babel-plugin-transform-relative-paths`.

In 0.2.4 this line works `var folders = require('../build/Release/platform-folders');`
the current line `var folders = require('./build/Release/platform-folders');` in 0.2.5 doesn't work for me under Linux/Windows.

**Comment by kingjan1999** [comment]
Yeah, I thought i could omit it (it worked for me). Reverted with 8960b42 (version 0.2.6)
